spring:
  application:
    name: miniapollo
management:
  endpoints:
    web:
      exposure:
        include: health, info
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{requestId}] %msg%n"